name: Build backend
 
on:
  workflow_dispatch:
  push:
    

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 2
      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          registry-url: https://npm.pkg.github.com/
      - name: Install dependencies
        run: npm install
      - name: Run build
        run: npm run build:apps:backend
      - name: npm publish
        working-directory: ./apps/backend
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUBTOKEN}}
